name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Unit test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      
      - run: npm ci

      - run: npm run test
